# Generated by Django 3.1 on 2020-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200904_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
    ]
